travis:
  secure:
    BINSTAR_TOKEN: qf4eNzzcoJz92UG1Gc0yLRrJvH+DSe6N7znOUyvgdRmvCpebewX2DoMTd+zfCoSGwqh+X7n8Q4Uxmas5FO8H6+uPmAzUUhzg+toVSD6j2fIVBiOsAGD+SdzDc3DzhYlLSqa+cOWCwPWP1O+I5KrOH7Q2Ehtup2zfgFqqqEWc9n+/QYRAUEpYluO+o4TNGaSMx2TQ47L1sTfNeK3c0xzoA/ezmxrmTbDGuW9vJFAmTbAmNmEubs5MBm2JltG6n7ZlxPf1Or9hQIgOpqpQmRZrDkxhB+EbAFeAAEBlEnhfYCGdVZtFlKUpFpUcH1Uhdzpq5fCrn4NY6gMpmgP5rPMBB5M+Ehr/h2yGCawlUM2Yqu4Yz4DYKjobfAJ1mU1oq8FjjIXSVzM9QhqhmmwMNSPBxhQkjqqjs5aiS7CJvViUqaU+eoD4bzX9RZdP0VObR0bvBrYvtgmXS0FzahHAfDMZHbowzJCaD8Smp1u650kKp/RpNDx+Udu73eKIhENAh20D23fhdKh7UcOi+EqHbWpkr9CtoPHoCOJjlu54rv1uGbMcVT7boiieSNb8pv760f+KXi7j3Kw0s/kdFxX+wR5wJgYWTwkM4rKfyIjnQepIhgmt+aCk/2BBQbtnPISLR/ioTFsm2TO5Lh71I7zRHyI5MR38lE9EqleH1tOjL4iD3MI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
